/**
 * Validation Agent
 * Verifies required output fields and contracts generated by node executions.
 */
export class ValidationAgent {
  /**
   * Validates step output against expectations
   * @param {Object} node 
   * @param {Object} result 
   * @returns {{ isValid: boolean, missingFields: Array, errors: Array }}
   */
  static validate(node, result) {
    if (!result) {
      return {
        isValid: false,
        missingFields: ['result'],
        errors: ['Execution agent returned empty or undefined result']
      };
    }

    const { data = {} } = node;
    const { provider, action, validationRules = {} } = data;
    const missingFields = [];
    const errors = [];

    // Explicit custom validation rules
    if (validationRules.requiredFields && Array.isArray(validationRules.requiredFields)) {
      for (const field of validationRules.requiredFields) {
        if (result[field] === undefined || result[field] === null || result[field] === '') {
          missingFields.push(field);
        }
      }
    }

    // Provider-specific contract validation
    if (provider === 'gmail' && (action === 'send_email' || action === 'sendMail')) {
      if (!result.messageId && !result.id) {
        missingFields.push('messageId');
      }
    }

    if (provider === 'slack' && (action === 'post_message' || action === 'postMessage')) {
      if (!result.ts && !result.type) {
        missingFields.push('ts');
      }
    }

    if (provider === 'google-sheets' && (action === 'append_row' || action === 'appendRow')) {
      if (!result.updates && !result.updatedRange) {
        missingFields.push('updatedRange');
      }
    }

    if (missingFields.length > 0) {
      errors.push(`Missing required output fields: ${missingFields.join(', ')}`);
    }

    return {
      isValid: errors.length === 0,
      missingFields,
      errors
    };
  }
}
